- name: Stand up webapp container
  docker:
    name: validatorsripplecom_web
    image: "quay.io/ripple/validators.ripple.com:{{deploy_environment}}"
    registry: "https://quay.io/v1/"
    email: ops@ripple.com
    username: "{{webapp_docker_username}}"
    password: "{{webapp_docker_password}}"
    state: reloaded
    pull: always
    expose:
      - 1337
    env:
      DATABASE_URL: "{{webapp_database_url}}"
